package view;
import DAO.DAO_postgreSQL.ClasseDAO;
import DAO.DAO_postgreSQL.PersonagemDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Personagem;

/**
 *
 * @author Patrick
 */
public class ApagarPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form ApagarPersonagem
     */
    
    private final Color vermelhoEscuro = new Color(30,0,0);
    private final Color vermelhoClaro = new Color(54,0,0);
    private PersonagemDAO personDAO = null;
    
    
    public ApagarPersonagem() {
        initComponents();
        
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        super.setLocationRelativeTo(null);
        
        
//========== ADICIONANDO DADOS NO COMBO BOX DE NOMES E IDs DE PERSONAGENS:===================

        try{
                this.personDAO = new PersonagemDAO();
                ClasseDAO classDAO = new ClasseDAO();
                
                
                List<Personagem> persons = personDAO.obter_personagens();
                DefaultTableModel dtm = new DefaultTableModel();
                dtm.setColumnIdentifiers( (String[])  new String[]{"Nome", "classe"} );
                
                String[] nomesClasses = classDAO.obter_nomes_classes();
                
                for (Personagem personagem : persons){
                    
                     dtm.addRow(
                             new String[]{
                                    personagem.getNome(), 
                                    ""+nomesClasses[ personagem.getClasse_id()-1 ]
                             } 
                     );
                }

      // INICIALIZANDO A TABELA "COM OS NOMES E CLASSES DOS PERSONAGENS":
              
                 this.table_nomes_classes.setModel(dtm);
                
       }catch(NullPointerException npe){
           JOptionPane.showMessageDialog(null, "Não foi possível se conectar com o banco de dados!!!", "Error!!!", JOptionPane.ERROR_MESSAGE);                 
           System.out.println(npe);
           this.dispose();
       }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_fundo_nome_personagem = new javax.swing.JPanel();
        lab_frase3 = new javax.swing.JLabel();
        lab_frase4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nomes_classes = new javax.swing.JTable();
        pnl_fundo_ID_personagem = new javax.swing.JPanel();
        lab_frase1 = new javax.swing.JLabel();
        combo_id_personagem = new javax.swing.JComboBox<>();
        lab_frase2 = new javax.swing.JLabel();
        btn_apagar_personagem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apagar personagem");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -10, 330, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        btn_voltar.setBackground(new java.awt.Color(51, 51, 51));
        btn_voltar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar.setText("Voltar");
        btn_voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 40));

        jTabbedPane1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N

        pnl_fundo_nome_personagem.setBackground(new java.awt.Color(30, 0, 0));
        pnl_fundo_nome_personagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_fundo_nome_personagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_fundo_nome_personagemMouseExited(evt);
            }
        });
        pnl_fundo_nome_personagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_frase3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase3.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase3.setText("Selecione o nome do personagem");
        pnl_fundo_nome_personagem.add(lab_frase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -10, 280, 70));

        lab_frase4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase4.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase4.setText("que deseja remover:");
        pnl_fundo_nome_personagem.add(lab_frase4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 170, 60));

        jLabel3.setText("OU");
        pnl_fundo_nome_personagem.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-23, 56, 30, 50));

        table_nomes_classes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        table_nomes_classes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_nomes_classes.setSelectionBackground(new java.awt.Color(255, 0, 0));
        table_nomes_classes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table_nomes_classes);

        pnl_fundo_nome_personagem.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 440, 170));

        jTabbedPane1.addTab("por Nome", pnl_fundo_nome_personagem);

        pnl_fundo_ID_personagem.setBackground(new java.awt.Color(30, 0, 0));
        pnl_fundo_ID_personagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_fundo_ID_personagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_fundo_ID_personagemMouseExited(evt);
            }
        });
        pnl_fundo_ID_personagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_frase1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase1.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase1.setText("Selecione o ID do personagem");
        pnl_fundo_ID_personagem.add(lab_frase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 40));

        combo_id_personagem.setBackground(new java.awt.Color(102, 102, 102));
        combo_id_personagem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        combo_id_personagem.setForeground(new java.awt.Color(255, 255, 255));
        combo_id_personagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        pnl_fundo_ID_personagem.add(combo_id_personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 210, 30));

        lab_frase2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase2.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase2.setText("que deseja remover:");
        pnl_fundo_ID_personagem.add(lab_frase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 40));

        jTabbedPane1.addTab("por ID", pnl_fundo_ID_personagem);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 500, 340));

        btn_apagar_personagem.setBackground(new java.awt.Color(51, 51, 51));
        btn_apagar_personagem.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_apagar_personagem.setForeground(new java.awt.Color(255, 255, 255));
        btn_apagar_personagem.setText("Apagar personagem");
        btn_apagar_personagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_apagar_personagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_apagar_personagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagar_personagemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_apagar_personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background game.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
         this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    
    private void btn_apagar_personagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagar_personagemActionPerformed

        String idSelecionado = this.combo_id_personagem.getSelectedItem().toString();
        
        if( idSelecionado !="Selecione"){
                boolean deletouComSucesso = this.personDAO.deletar_personagem_por_ID( Integer.parseInt(idSelecionado) );

                if(deletouComSucesso) 
                    JOptionPane.showMessageDialog(null, "Personagem com ID: "+idSelecionado+" foi apagado com sucesso!!!", "Sucesso!!!", JOptionPane.INFORMATION_MESSAGE);                 
                else
                    JOptionPane.showMessageDialog(null, "Não foi possível apagar o personagem! \n Verifique sua conexão com o banco de dados!!!", "Error!!!", JOptionPane.ERROR_MESSAGE);                 
                
                this.dispose();
                
        }else{
             JOptionPane.showMessageDialog(null, "Por favor, selecione o ID de um personagem correto!!!", "Error!!!", JOptionPane.ERROR_MESSAGE);                 
        }
    }//GEN-LAST:event_btn_apagar_personagemActionPerformed

    
    
    private void pnl_fundo_ID_personagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_fundo_ID_personagemMouseEntered
          this.pnl_fundo_ID_personagem.setBackground( this.vermelhoClaro ); 
    }//GEN-LAST:event_pnl_fundo_ID_personagemMouseEntered

    private void pnl_fundo_ID_personagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_fundo_ID_personagemMouseExited
          this.pnl_fundo_ID_personagem.setBackground( this.vermelhoEscuro);
    }//GEN-LAST:event_pnl_fundo_ID_personagemMouseExited

    
    private void pnl_fundo_nome_personagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_fundo_nome_personagemMouseEntered
         this.pnl_fundo_nome_personagem.setBackground( this.vermelhoClaro);
    }//GEN-LAST:event_pnl_fundo_nome_personagemMouseEntered

    private void pnl_fundo_nome_personagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_fundo_nome_personagemMouseExited
         this.pnl_fundo_nome_personagem.setBackground( this.vermelhoEscuro );
    }//GEN-LAST:event_pnl_fundo_nome_personagemMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApagarPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar_personagem;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<String> combo_id_personagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lab_frase1;
    private javax.swing.JLabel lab_frase2;
    private javax.swing.JLabel lab_frase3;
    private javax.swing.JLabel lab_frase4;
    private javax.swing.JPanel pnl_fundo_ID_personagem;
    private javax.swing.JPanel pnl_fundo_nome_personagem;
    private javax.swing.JTable table_nomes_classes;
    // End of variables declaration//GEN-END:variables
}
