/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Patrick
 */
public class ApagarPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form ApagarPersonagem
     */
    public ApagarPersonagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnl_fundo_ID_personagem = new javax.swing.JPanel();
        lab_frase1 = new javax.swing.JLabel();
        combo_id_personagem = new javax.swing.JComboBox<>();
        btn_botao_esquerdo = new javax.swing.JButton();
        lab_frase2 = new javax.swing.JLabel();
        pnl_fundo_nome_personagem = new javax.swing.JPanel();
        lab_frase3 = new javax.swing.JLabel();
        lab_frase4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_botao_direito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apagar personagem");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 330, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 70));

        pnl_fundo_ID_personagem.setBackground(new java.awt.Color(30, 0, 0));
        pnl_fundo_ID_personagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_frase1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase1.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase1.setText("Selecione o ID do personagem");
        pnl_fundo_ID_personagem.add(lab_frase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        combo_id_personagem.setBackground(new java.awt.Color(102, 102, 102));
        combo_id_personagem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        combo_id_personagem.setForeground(new java.awt.Color(255, 255, 255));
        combo_id_personagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        pnl_fundo_ID_personagem.add(combo_id_personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 30));

        btn_botao_esquerdo.setBackground(new java.awt.Color(51, 51, 51));
        btn_botao_esquerdo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_botao_esquerdo.setForeground(new java.awt.Color(255, 255, 255));
        btn_botao_esquerdo.setText("Apagar personagem");
        btn_botao_esquerdo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_botao_esquerdo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_fundo_ID_personagem.add(btn_botao_esquerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 160, 30));

        lab_frase2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase2.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase2.setText("que deseja remover:");
        pnl_fundo_ID_personagem.add(lab_frase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        pnl_fundo_nome_personagem.setBackground(new java.awt.Color(44, 0, 0));
        pnl_fundo_nome_personagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_frase3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase3.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase3.setText("Selecione o nome do personagem");
        pnl_fundo_nome_personagem.add(lab_frase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 280, 50));

        lab_frase4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab_frase4.setForeground(new java.awt.Color(255, 255, 255));
        lab_frase4.setText("que deseja remover:");
        pnl_fundo_nome_personagem.add(lab_frase4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 60));

        jList1.setBackground(new java.awt.Color(51, 51, 51));
        jList1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        pnl_fundo_nome_personagem.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 220, 180));

        btn_botao_direito.setBackground(new java.awt.Color(51, 51, 51));
        btn_botao_direito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_botao_direito.setForeground(new java.awt.Color(255, 255, 255));
        btn_botao_direito.setText("Apagar personagem");
        btn_botao_direito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_botao_direito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_fundo_nome_personagem.add(btn_botao_direito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, 30));

        pnl_fundo_ID_personagem.add(pnl_fundo_nome_personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 340, 320));

        getContentPane().add(pnl_fundo_ID_personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background game.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApagarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApagarPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_botao_direito;
    private javax.swing.JButton btn_botao_esquerdo;
    private javax.swing.JComboBox<String> combo_id_personagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_frase1;
    private javax.swing.JLabel lab_frase2;
    private javax.swing.JLabel lab_frase3;
    private javax.swing.JLabel lab_frase4;
    private javax.swing.JPanel pnl_fundo_ID_personagem;
    private javax.swing.JPanel pnl_fundo_nome_personagem;
    // End of variables declaration//GEN-END:variables
}
