/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import view.Consulta_Personagem;
/**
 *
 * @author Patrick
 */
public class GerenciarPersonagem extends java.awt.Frame {

    /**
     * Creates new form GerenciarPersonagem
     */
    public GerenciarPersonagem() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lab_fundo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(902, 559));
        setPreferredSize(new java.awt.Dimension(902, 559));
        setSize(new java.awt.Dimension(902, 559));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Criar personagem");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, 210));

        jButton2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Alterar personagem");
        jButton2.setEnabled(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 470, 210));

        jButton3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        jButton3.setText("Excluir personagem");
        jButton3.setEnabled(false);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 470, 200));

        jButton4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        jButton4.setText("Consultar personagem");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 440, 200));

        jPanel1.setBackground(new java.awt.Color(36, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(911, 546));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciar personagem");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 360, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 70));

        lab_fundo.setForeground(null);
        lab_fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Patrick\\Pictures\\Background menu RPG.jpg")); // NOI18N
        add(lab_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 66, 910, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          new Consulta_Personagem().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarPersonagem().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab_fundo;
    // End of variables declaration//GEN-END:variables
}
