/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
/**
 *
 * @author Patrick
 */
public class GerenciarPersonagem extends javax.swing.JFrame { //java.awt.Frame

    /**
     * Creates new form GerenciarPersonagem
     */
    public GerenciarPersonagem() {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE );
        this.setLocationRelativeTo( null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_criar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_consulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lab_fundo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(902, 559));
        setPreferredSize(new java.awt.Dimension(902, 559));
        setSize(new java.awt.Dimension(902, 556));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_criar.setBackground(new java.awt.Color(102, 102, 102));
        btn_criar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        btn_criar.setForeground(new java.awt.Color(204, 204, 204));
        btn_criar.setText("Criar personagem");
        btn_criar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        btn_criar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_criar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 400, 140));

        btn_alterar.setBackground(new java.awt.Color(102, 102, 102));
        btn_alterar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(204, 204, 204));
        btn_alterar.setText("Alterar personagem");
        btn_alterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        btn_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alterar.setEnabled(false);
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 400, 140));

        btn_excluir.setBackground(new java.awt.Color(102, 102, 102));
        btn_excluir.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(204, 204, 204));
        btn_excluir.setText("Excluir personagem");
        btn_excluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir.setEnabled(false);
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 400, 140));

        btn_consulta.setBackground(new java.awt.Color(102, 102, 102));
        btn_consulta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        btn_consulta.setForeground(new java.awt.Color(204, 204, 204));
        btn_consulta.setText("Consultar personagem");
        btn_consulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        btn_consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 400, 140));

        jPanel1.setBackground(new java.awt.Color(36, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), null, null));
        jPanel1.setPreferredSize(new java.awt.Dimension(911, 546));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciar personagem");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 360, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 80));

        lab_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background game.jpg"))); // NOI18N
        getContentPane().add(lab_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 66, 910, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
          System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaActionPerformed
          new ConsultaPersonagem().setVisible(true);
    }//GEN-LAST:event_btn_consultaActionPerformed

    private void btn_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarActionPerformed
          new CadastroPersonagem().setVisible(true);
    }//GEN-LAST:event_btn_criarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarPersonagem().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_consulta;
    private javax.swing.JButton btn_criar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab_fundo;
    // End of variables declaration//GEN-END:variables
}
